# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/klefevre/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  ansible
  asdf
  archlinux
  aws
  command-not-found
  common-aliases
  copypath
  copyfile
  cp
  direnv
  docker
  encode64
  extract
  fancy-ctrl-z
  fzf
  gcloud
  git
  git-extras
  git-flow
  gnu-utils
  golang
  gpg-agent
  httpie
  helm
  jsontools
  kubectl
  man
  mosh
  pass
  pip
  rust
  shrink-path
  ssh-agent
  sudo
  systemd
  terraform
  thefuck
  tig
  tmux
  ubuntu
  virtualenv
  virtualenvwrapper
  vscode
  zsh-navigation-tools
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Tilix fix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi
# User configuration

# Load zoxide
eval "$(zoxide init zsh)"

# Completion
source <(kubectl completion zsh)
source <(minikube completion zsh)
source <(helm completion zsh)

kind completion zsh > $ZSH/completions/_kind
gopass completion zsh > $ZSH/completions/_gopass
flux completion zsh > $ZSH/completions/_flux
eval "$(aws-vault --completion-script-zsh)"

. /etc/os-release

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/klefevre/google-cloud-sdk/path.zsh.inc' ]; then . '/home/klefevre/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/klefevre/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/klefevre/google-cloud-sdk/completion.zsh.inc'; fi

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

# Aliases
alias less=$PAGER
alias zless=$PAGER
alias more=$PAGER
alias vim='nvim'
alias suroot='sudo -E -s'
alias pubkey='ssh-keygen -y -f'

# GNU Rust aliases
alias ls='exa --icons'
if [ $ID = "arch" ]; then
  alias cat='bat'
elif [ $ID = "ubuntu" ]; then
  alias cat='batcat'
fi
alias tree='exa --tree --icons'
alias fd='fdfind'
alias ps='procs'
alias du='dust -r'
# alias sed='sd'
alias htop='btm'
alias grep='rg'
alias dmesg='rmesg'
alias pass='gopass'

# Completion
autoload -U compinit && compinit

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export VAULT_FORMAT=json
export VAULT_ADDR="http://localhost:8200"

export GITHUB_TOKEN=$(pass show -o github.com/archifleks token)
export GITGUARDIAN_API_KEY=$(pass show -o gitguardian.com/apikey)

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Man
export MANPAGER='nvim +Man!'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

